### ISSUE TITLE
Pack of questions

### ISSUE THREAD

**Issue by xcom169** [AlexeySemigradsky/OpenWrt-Breed#1]
Is it also working with OpenWrt 19.07.4 ?

I just need to flash the image? No other steps needed?

**Comment by AlexeySemigradsky** [comment]
> Is it also working with OpenWrt 19.07.4?

Currently I can't test it.

> I just need to flash the image? No other steps needed?

Yes, if you've already installed Breed.

**Comment by graddotdev** [comment]
> Is it also working with OpenWrt 19.07.4?

I've only tested this script with OpenWrt 18.06.

> I just need to flash the image? No other steps needed?

Yes, if you've already installed Breed.

PS My apologies for the late reply.

**Comment by graddotdev** [comment]
@xcom169, I tested this script with OpenWrt 19.07.4. Works great.
